 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/product_details", type: :request do
  # Admin::ProductDetail. As you add validations to Admin::ProductDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::ProductDetail.create! valid_attributes
      get admin_product_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_detail = Admin::ProductDetail.create! valid_attributes
      get admin_product_detail_url(admin_product_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_product_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      product_detail = Admin::ProductDetail.create! valid_attributes
      get edit_admin_product_detail_url(admin_product_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::ProductDetail" do
        expect {
          post admin_product_details_url, params: { admin_product_detail: valid_attributes }
        }.to change(Admin::ProductDetail, :count).by(1)
      end

      it "redirects to the created admin_product_detail" do
        post admin_product_details_url, params: { admin_product_detail: valid_attributes }
        expect(response).to redirect_to(admin_product_detail_url(@admin_product_detail))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::ProductDetail" do
        expect {
          post admin_product_details_url, params: { admin_product_detail: invalid_attributes }
        }.to change(Admin::ProductDetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_product_details_url, params: { admin_product_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_product_detail" do
        product_detail = Admin::ProductDetail.create! valid_attributes
        patch admin_product_detail_url(admin_product_detail), params: { admin_product_detail: new_attributes }
        product_detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_product_detail" do
        product_detail = Admin::ProductDetail.create! valid_attributes
        patch admin_product_detail_url(admin_product_detail), params: { admin_product_detail: new_attributes }
        product_detail.reload
        expect(response).to redirect_to(admin_product_detail_url(product_detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        product_detail = Admin::ProductDetail.create! valid_attributes
        patch admin_product_detail_url(admin_product_detail), params: { admin_product_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_product_detail" do
      product_detail = Admin::ProductDetail.create! valid_attributes
      expect {
        delete admin_product_detail_url(admin_product_detail)
      }.to change(Admin::ProductDetail, :count).by(-1)
    end

    it "redirects to the admin_product_details list" do
      product_detail = Admin::ProductDetail.create! valid_attributes
      delete admin_product_detail_url(admin_product_detail)
      expect(response).to redirect_to(admin_product_details_url)
    end
  end
end
