default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 
  timeout: 5000

development:
  <<: *default
  database: HN_ruby_2022_phone_ecommerce

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 
  timeout: 5000
  database: HN_ruby_2022_phone_ecommerce
